version: "3"
services:
    ssp:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - "8080:8080"
        volumes:
            - .:/app
    redis:
        image: "redis:alpine"